include_configs:
  - ../train/diffusion/diffusion_16x16x16_dense.yaml
  - data.yaml

name: 'fvdb_example_data/diffusion_dense'

vae_config: "configs/fvdb_example_data/train_vae_16x16x16_dense.yaml"
vae_checkpoint: "checkpoints/fvdb_example_data/coarse_vae/last.ckpt"
