include_configs:
  - ../train/vae/vae_16x16x16_dense_residual.yaml
  - dataset.yaml

name: 'waymo_scube_test/VAE_64x64x64_dense_height_down2_residual'

# data
batch_size: 1
accumulate_grad_batches: 16
voxel_size: 0.4
use_fvdb_loader: true
_fvdb_grid_type: 'vs04'
_input_slect_ids: [0]
_input_frame_offsets: [0]
_sup_slect_ids: [0]
_sup_frame_offsets: [0]
grid_crop_bbox_min: [-10.24, -51.2, -12.8]
grid_crop_bbox_max: [92.16, 51.2, 38.4]
grid_crop_augment: true
grid_crop_augment_range: [6.4, 6.4, 1.6]
replace_all_car_with_cad: true # rather than using bounding box, using CAD model makes more sense


# adjust input setting - use semantic and intensity
use_input_normal: false
use_input_semantic: true
use_input_intensity: false
num_semantic: 23
dim_semantic: 32


# adjust supervision - add semantic supervision
supervision:
  semantic_weight: 20.0
  normal_weight: 0

# adjust network
cut_ratio: 32
remain_h: true
use_hash_tree: false # use_hash_tree conflict with remain_h
tree_depth: 3

network:
  unet:
    params:
      neck_bound: [32, 32, 32] # means [-32, +32] for each dimension
      pooling_level: [2]
      neck_dense_type: "HAND_CRAFTED"